### ISSUE TITLE
problems with umlauts due to MySQL collation

### ISSUE THREAD

**Issue by koelnconcert** [datacite/mds#261]
If you first register (via API) `10.5072/A` and afterwards `10.5072/Ä` (german umlaut) both are minted in handle server. But you will not find the latter one in MDS! This is due to the used collation `utf`, which uses a non-binary comparison (see [MySql manual](http://dev.mysql.com/doc/refman/5.0/en/case-sensitivity.html)):

```
SELECT 'a' = 'A';      ->  1
SELECT 'Ä' = 'A';      ->  1
```

So when you register `10.5072/Ä` via API you will update `10.5072/A` in MDS but register `10.5072/Ä` in handle server!

The best way would be to use `utf8-bin` collation at least for DOI. We then have to ensure that we only work on _normalized_ (=uppercased) DOIs, to have the same rules for uniqueness as the handle server.

**Comment by mfenner** [comment]
@koelnconcert is this still relevant?

**Comment by koelnconcert** [comment]
I believe so.
