### ISSUE TITLE
additional parameters causes API to redirect badly

### ISSUE THREAD

**Issue by koelnconcert** [datacite/mds#301]
In case of an API call with unsupported parameters, e.g.

```
POST /doi?doi=10.5072/foo&url=http://example.com
```

MDS returns with a redirect to the login page.

In addition the redirect is non functional, because it uses the internal address (e.g. https://test.ec2.datacite.org:8443/mds/login)

**Comment by koelnconcert** [comment]
looks like the only allowed parameter `testMode` causes the same problem, too.

**Comment by ioverka** [comment]
This bug currently prevents us from executing automatic tests and therefore a fix would be highly appreciated. Thanks!
