### ISSUE TITLE
alternateIdentifier which is a uri is refused

### ISSUE THREAD

**Issue by alastairduncan** [datacite/mds#309]
I've submitting a request to the test server to register metadata with a uri in the alternateIdentifier field and it is being refused because the domain of the host is not the same as that of the domain for the registered account. 

response content: [url] domain of URL is not allowed

I can understand why this may be a good thing but it in this case the alternate identifier is a purl which will then be resolved to a host within the registered domain. The alternateIdentifierType that I've tried using is "uri", I've also tried "string" but there is something trying to be intelligent behind the scenes which is identifying the alternateIdentifier as a url. I think the case of an identifier which is a purl is a valid case where simple domain matching is not the best way to check if the identifier is valid. Is there anything I can do to get around this problem?

Thanks

**Comment by koelnconcert** [comment]
The domain is not checked upon metadata upload. In particular the content of alternateIdentifiers is not even checked for well-formed URIs.

I'm assuming you use our API. Are you sure you got this message when uploading the metadata and not when registering the DOI (POST /doi)? 

Could you provide your username and time and date of your request so I could have a look at the logs? If this is too confidential for you just sent it to tech@datacite.org.

**Comment by alastairduncan** [comment]
You are correct it was the registration step not the metadata upload and its the REST API being used.

2015-11-23 14:35:44,183 DEBUG sendHttpRequest POST https://mds.test.datacite.org/doi HTTP/1.1
2015-11-23 14:35:44,541 DEBUG sendHttpRequest resopnse status: HTTP/1.1 400 Bad Request
2015-11-23 14:35:44,541 DEBUG sendHttpRequest response content: [url] domain of URL is not allowed

I've sent the username to the email address supplied along with the metadata uploaded.

**Comment by koelnconcert** [comment]
Ok. Then this is expected behaviour. For every account there is an individual list of allowed domains for the landing page URLs. You can see the list when logged in via browser via the "My account" link. Please contact your allocator regarding additions to this list.
