### ISSUE TITLE
The citation does not reflect the current version of metadata

### ISSUE THREAD

**Issue by quyen** [datacite/mds#318]
Hi,

We are the member of datacite. We are using mds api to let our users to generate dois for their assets in from our service, at https://fairdomhub.org
Recently I uploaded the second version of metadata, to update the publisher.
However, the citation bit is not updated with the current version.
http://data.datacite.org/10.15490/seek.1.investigation.56

Is this intended or is it a bug?

Regards,
Quyen

**Comment by koelnconcert** [comment]
Neither of them. It is a performance/scaling issue we are aware and working on. It can currently take up 72hours until metadata updated are indexed and accessible via our public interface (search, oai, data).

So for now you probably just have to be patient.
