### ISSUE TITLE
Creating new DOIs fails if publicationYear != != '[\d]{4}'

### ISSUE THREAD

**Issue by ioverka** [datacite/mds#322]
System: https://mds.test.datacite.org/ 

The [DataCite schema v 4.0](http://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf) specifies a couple of "standard machine‐recognizable codes" which should be used if a required property is unavailable (see appendix 3). Using "(:none)" as value for the publicationYear returns an XML error though:

```
xml error: cvc-pattern-valid: Value '(:none)' is not facet-valid with respect to pattern '[\d]{4}' for type '#AnonType_publicationYearresource'.
```

Complete XML is:
```

<?xml version='1.0' encoding='UTF-8'?>
<resource xmlns='http://datacite.org/schema/kernel-3' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd'>
<identifier identifierType='DOI'>10.15771/7888xxisk</identifier>
<creators>
	<creator>
		<creatorName>Max Planck</creatorName>
	</creator>
</creators>
<titles>
	<title>Test</title>
</titles>
<publisher>Max Planck Society</publisher>
<publicationYear>(:none)</publicationYear>
</resource>
```

**Comment by ioverka** [comment]
This issue is caused by DataCite, see https://github.com/datacite/mds/issues/322

**Comment by ioverka** [comment]
Sorry, I closed the wrong issue ;)

**Comment by mfenner** [comment]
For `publicationYear`, which is a numeric field, use `0000` if the publication year is not known. There is also guidance in the documentation on how to handle some specific situations.

**Comment by ioverka** [comment]
Thanks a lot for the swift reply. The current schema documentation doesn't include a reference to the value `0000`. The section "Guidance for handling missing mandatory property values" under the heading "PublicationYear—Additional guidance" refers to appendix 3.

**Comment by mfenner** [comment]
Yes indeed. We should fix this.

**Comment by mfenner** [comment]
Closing this issues, as this should be fixed in The schema dokumentation.
