### ISSUE TITLE
MDS Test points to the wrong handle System

### ISSUE THREAD

**Issue by kjgarza** [datacite/mds#331]
When you create a DOI in the MDS TEst the links in the webpage point to the wrong handle server 

which is: 
http://test.datacite.org/handle/10.5072/UU01-8QRDTN 

But it should be:
http://handle.test.datacite.org/10.5072/UU01-8QRDTN 

https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/312

**Comment by kjgarza** [comment]
There is also a ticket in zoho #7839 bug MDS test

**Comment by kjgarza** [comment]
Teh change should be here:  https://github.com/datacite/mds/blob/master/src/main/webapp/WEB-INF/views/datasets/show.jspx#L8

But the variable handleProxy oddly points to doi.org  instead that to an env.

**Comment by mfenner** [comment]
Added redirect rule in S3 for `test.datacite.org`.
