### ISSUE TITLE
Test instance does not accept a metadata POST

### ISSUE THREAD

**Issue by walterMPDL** [datacite/mds#336]
Hi datacite-team,

we are having some issues concerning the test instance (https://mds.test.datacite.org/). If we are trying to POST some metadata to https://mds.test.datacite.org/metadata the response is 404 AbstractController::ActionNotFound
Sorry if we missed a change there, but I couldn't find anything in the API documentation.

Best Regards,
Matthias Walter

**Comment by mfenner** [comment]
Can you provide the request you are doing, e.g. in curl? The API endpoint is correct, but we can't really say more based on the info you provided.

**Comment by walterMPDL** [comment]
curl -X POST \
  https://mds.test.datacite.org/metadata \
  -H 'Authorization: Basic  XXX' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: f19708de-9579-47d1-814a-a4fdecd8e360' \
  -d '<?xml version="1.0" encoding="UTF-8"?>
<doi:resource xmlns:doi="http://datacite.org/schema/kernel-3"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
   <doi:identifier identifierType="DOI">10.5072/pure.item_3001051</doi:identifier>
   <doi:version>1</doi:version>
   <doi:creators>
      <doi:creator>
         <doi:creatorName>Test, Test</doi:creatorName>
         <doi:affiliation>Collections, Max Planck Digital Library, Max Planck Society</doi:affiliation>
      </doi:creator>
   </doi:creators>
   <doi:titles>
      <doi:title>test</doi:title>
   </doi:titles>
   <doi:subjects>
      <doi:subject>keyword1, keyword2, keyword3</doi:subject>
   </doi:subjects>
   <doi:publicationYear>2018</doi:publicationYear>
   <doi:publisher>Test</doi:publisher>
   <doi:dates>
      <doi:date dateType="Issued">2018</doi:date>
   </doi:dates>
   <doi:resourceType resourceTypeGeneral="Text">article</doi:resourceType>
   <doi:formats>
      <doi:format>text/html</doi:format>
   </doi:formats>
   <doi:sizes>
      <doi:size>25</doi:size>
   </doi:sizes>
</doi:resource>
'

**Comment by walterMPDL** [comment]
That's our request (authentication removed), which was working fine until now (can't say how long it really worked, as we have not been testing this for a while now)

**Comment by mfenner** [comment]
There are two things in your example that you should double-check:

* use content type `text/plain;charset=UTF-8`. My guess is you use something else (e.g. `application/x-www-form-urlencoded`). Because the XML is not processed correctly, the DOI in there is not found and thus the 404 error
* please don't use the `doi` namespace in the XML.

Best,

Martin

**Comment by mfenner** [comment]
I now see your request in our bug tracker, and you are indeed using `application/x-www-form-urlencoded`. That will not work, and also has not in the past. I will try to generate a better error message.

**Comment by walterMPDL** [comment]
you were right, i was using text/plain insted of application/xml in my CURL but it is not working with application/xml aswell
```
curl -X POST \
  https://mds.test.datacite.org/metadata \
  -H 'Authorization: Basic  XXX' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/xml' \
  -H 'Postman-Token: cf7e69d5-5f77-4839-bfb5-60e5d51ba5b1' \
  -d '<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
   <identifier identifierType="DOI">10.5072/pure.item_3001051</identifier>
   <version>1</version>
   <creators>
      <creator>
         <creatorName>Test, Test</creatorName>
         <affiliation>Collections, Max Planck Digital Library, Max Planck Society</affiliation>
      </creator>
   </creators>
   <titles>
      <title>test</title>
   </titles>
   <subjects>
      <subject>keyword1, keyword2, keyword3</subject>
   </subjects>
   <publicationYear>2018</publicationYear>
   <publisher>(:unas)</publisher>
   <dates>
      <date dateType="Issued">2018</date>
   </dates>
   <resourceType resourceTypeGeneral="Text">article</resourceType>
   <formats>
      <format>text/html</format>
   </formats>
   <sizes>
      <size>25</size>
   </sizes>
</resource>
'
```

**Comment by mfenner** [comment]
Walter, please use content-type `application/xml` or `text/plain`. I see several requests from you all using `application/x-www-form-urlencoded`, which is not going to work.

**Comment by walterMPDL** [comment]
Not really, I am using application/xml now, as you can see above

**Comment by mfenner** [comment]
I am not seeing an `xmlns`, similar to `xmlns="http://datacite.org/schema/kernel-3"`.

**Comment by mfenner** [comment]
I implemented proper error responses for content_type `application/x-www-form-urlencoded` and missing `xmlns`. Closing this issue.

**Comment by walterMPDL** [comment]
Thank you for your help. If we remove the explicit doi-namespace definitions and define a global namespache 'xmlns="http://datacite.org/schema/kernel-3"', everything seems to work fine. Has something changed here, that we missed? Because we were using the old XML for a long period now, and it worked fine all the time.

**Comment by ioverka** [comment]
Hi, just as a follow-up on this: Unfortunately, the XML returned by the DataCite Rest API Get metadata route can no longer be used for Put and Post because it actually uses the doi namespace in the XML, e.g.

```
curl -k --user xxx:yyy https://mds.datacite.org/metadata/10.17617/2.2057711
<?xml version="1.0" encoding="UTF-8"?>
<doi:resource xmlns:doi="http://datacite.org/schema/kernel-3"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
   <doi:identifier identifierType="DOI">10.17617/2.2057711</doi:identifier>
   <doi:version>6</doi:version>
   <doi:creators>
      <doi:creator>
         <doi:creatorName>Van Turennout, Miranda</doi:creatorName>
         <doi:affiliation>Language Production Group Levelt , MPI for Psycholinguistics, Max Planck Society</doi:affiliation>
      </doi:creator>
   </doi:creators>
   <doi:titles>
      <doi:title>The electrophysiology of speaking: Investigations on the time course of semantic, syntactic, and phonological processing</doi:title>
   </doi:titles>
   <doi:language>eng</doi:language>
   <doi:subjects>
      <doi:subject subjectScheme="eterms:DDC"/>
   </doi:subjects>
   <doi:publicationYear>1997</doi:publicationYear>
   <doi:publisher>Radboud University Nijmegen</doi:publisher>
   <doi:dates>
      <doi:date dateType="Issued">1997</doi:date>
   </doi:dates>
   <doi:resourceType resourceTypeGeneral="Text">thesis</doi:resourceType>
   <doi:alternateIdentifiers>
      <doi:alternateIdentifier alternateIdentifierType="eterms:ISBN">90-76203-01-6</doi:alternateIdentifier>
   </doi:alternateIdentifiers>
   <doi:formats>
      <doi:format>application/pdf</doi:format>
   </doi:formats>
   <doi:sizes>
      <doi:size>9998569</doi:size>
   </doi:sizes>
```
